jobs:
  build:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java_version }}
        server-id: sonatype-nexus-snapshots
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      name: Build
      run: ./mvnw -B -q -ff -ntp verify
    - continue-on-error: true
      id: projectVersion
      name: Extract project Maven version
      run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate
        -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      if: github.event_name != 'pull_request' && matrix.java_version == '8' && endsWith(steps.projectVersion.outputs.version,
        '-SNAPSHOT')
      name: Deploy snapshot
      run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
    - continue-on-error: true
      if: github.event_name != 'pull_request' && matrix.java_version == '8'
      name: Generate code coverage
      run: ./mvnw -B -q -ff -ntp test
    - continue-on-error: true
      if: github.event_name != 'pull_request' && matrix.java_version == '8'
      name: Publish code coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '8'
        - '11'
        - '17'
        - '21'
        os:
        - ubuntu-20.04
name: Build and Deploy Snapshot
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions:
  contents: read
